# bundle exec jekyll serve
#--------------
# -- Settings --
# --------------

#coder table done by brittany walker 
#https://codepen.io/trekkiegirl/pen/mWLWJy


# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://www.hackbo.org"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-100454271-1"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "HackBo"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackBo"
  description: "Hackathon Clubes de Ciencia Bolivia Santa Cruz de la Sierra"
  image:       "images/hackbourl.png"

# Event information.
event:
  name:        "HackBo"
  description: "Clubes de Ciencia Bolivia"
  date:        "27 y 28 de Julio 2017"
  location:    "UPSA"

  hero:
    links:
      - text: "Aplica"
        href: "https://ferrufino.typeform.com/to/jDxP1F"
        class: "typeform-share link"
        data-mode: "2"
        target: ""
        data-toggle: ""
        data-content: ""
        id: "aplica-btn"
        clicked: "return trackFormViews();"
      - text: "Patrocinios"
        href: "mailto:clubesdecienciabolivia@gmail.com"
        class: "link"
        data-mode: ""
        target: ""
        toggle: "popover"
        content: "clubesdecienciabolivia@gmail.com"
        placement: "auto"
        trigger: "click"
        id: "patrocinios-btn"
        clicked: "return true;"


  about:
    description: >
      HackBo es el hackathon estudiantil m&aacute;s grande en Bolivia, donde apasionados por la tecnolog&iacute;a colaboran durante 24hrs.
      En equipos, compiten para desarrollar la mejor soluci&oacute;n de software o hardware
      y ganar uno de los tres primeros lugares, al igual que muchos premios!      

  # Info Sections
  info:
    sections:
      - image: "images/Disenha.png"
        title: "DISEÑA"
        description: >
          ¡Dise&ntilde;a bien tu proyecto! Deber&iacute;as de ser capaz de responder ¿Qu&eacute; necesidad soluciona mi propuesta?
          (C&iacute;vico, Salud, Social, Educaci&oacute;n, etc.)
      - image: "images/Desarrolla.png"
        title: "DESARROLLA"
        description: >
          Debe ser un proyecto de software o hardware.
          Si durante el hackathon tienes dudas, no te preocupes, tendr&aacute;s grandes mentores para que te asesoren ;)
      - image: "images/Presenta.png"
        title: "PRESENTA"
        description: >
          Aseg&uacute;rate que tu hack est&eacute; estable, y no te olvides de preparar tu presentaci&oacute;n ante los jueces. ¡Buena suerte!

  # Frequently asked questions.
  faq:
    - question: "Voy a participar solo o en equipo."
      answer: >
        Si es que vas a participar solo, necesitas saber programar, o bien en equipo (m&aacute;ximo 4) por lo menos una persona debe de saber programar para poder crear un desarrollo en 24hrs.
    - question: "Estoy estudiando mi segunda carrera ¿Puedo participar?"
      answer: >
        Lamentablemente no. Para validar tu participación, Clubes de Ciencia Bolivia considerara tu nivel de educación mas alto. Este es un evento para estudiantes de colegio o pregrado universitario.
    - question: "¿Necesito ser estudiante para participar en este Hackathon?"
      answer: >
        S&iacute;. S&oacute;lo estudiantes que est&eacute;n inscritos en universidad, o bien, &uacute;ltimos a&ntilde;os de colegio (con permiso de su tutor legal)
        pueden participar de este evento.
    - question: ¿Qué edad debo tener para participar en HackBo?
      answer: >
        Si bien nosotros no tenemos una edad definida, nuestros participantes generalmente están entre los 17 y los 25 años. Como regla, no admitimos estudiantes fuera de estas edades porque lo vemos contraproducente para la dinámica de equipo.
    - question: "¿Existe un c&oacute;digo de conducta?"
      answer: >
        S&iacute;, existe. Se debe de respetar el establecimiento, los componentes tecnol&oacute;gicos y dem&aacute;s participates del hackathon.
    - question: "¿Qu&eacute; es un Hackathon?"
      answer: >
        Un hackathon es un marat&oacute;n donde desarrolladores se juntan para crear un proyecto de Software o Hardware en 24hrs, presentando un prototipo que solucione un problema. (Al menos una persona de un equipo debe de saber programar)
    - question: "¿Qui&eacute;nes est&aacute;n organizando este evento?"
      answer: >
        [Clubes de Ciencia Bolivia](http://www.clubesdecienciabolivia.com/)
    - question: "¿Cu&aacute;nto cuesta?"
      answer: >
        Nada. Atender al Hackathon es gratis.
    - question: "¿D&oacute;nde es el evento?"
      answer: >
        El evento va ser realizado en la UPSA del 27 al 28 de Julio


  # Partners
  partner:
    - image: "images/upsa.png"

  patrocinadores:
    - image: "images/facebook-logo.png"

  logo:
    - image: "images/hackbo2x.png"
    - imageSmall: "images/hackbo.png"
    - imageCdeCBo: "images/CdeCbo.png"

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
